spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/influencehub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug

youtube:
  client-id: ${YOUTUBE_CLIENT_ID:}
  client-secret: ${YOUTUBE_CLIENT_SECRET:}
  redirect-uri: ${YOUTUBE_REDIRECT_URI:http://localhost:8080/api/v1/youtube/oauth/callback}
